name: lyf_echo
channels:
  - defaults
dependencies:
  - python=3.11.13
  - pip>=25
  - setuptools
  - wheel
  - pip:
      - matplotlib==3.10.8
      - networkx==3.6.1
      - numpy==2.4.3
      - pandas==3.0.1
      - pyarrow==20.0.0
      - pyyaml==6.0.3
      - scipy==1.17.1
      - tqdm==4.67.3
      - --extra-index-url=https://download.pytorch.org/whl/cu118
      - --find-links=https://data.pyg.org/whl/torch-2.6.0+cu118.html
      - torch==2.6.0+cu118
      - lightning==2.6.1
      - opt-einsum==3.4.0
      - optuna==4.8.0
      - ray==2.54.0
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt26cu118
      - torch-sparse==0.6.18+pt26cu118
      - torchdyn==1.0.6
      - torchmetrics==1.6.3
      - wandb==0.22.2
      - yacs==0.1.8
