[project]
name = "graph-transfer-gpp"
version = "0.1.0"
description = "Can You Hear Me Now? A new benchmark for long-range graph propagation"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "lightning>=2.5.5",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "opt-einsum>=3.4.0",
    "optuna>=4.5.0",
    "pandas>=2.3.3",
    "pyarrow==20.0.0",
    "ray>=2.50.1",
    "torch==2.6.0",
    "torch-geometric==2.7.0",
    "torch-scatter==2.1.2",
    "torch-sparse==0.6.18",
    "torchdyn>=1.0.6",
    "torchmetrics<1.7",
    "tqdm>=4.66.5",
    "wandb==0.22.2",
    "yacs>=0.1.8",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu118", marker = "sys_platform == 'linux'" },
]
torch-scatter = [
    { index = "pyg-cu118", marker = "sys_platform == 'linux'" },
]
torch-sparse = [
    { index = "pyg-cu118", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pyg-cu118"
url = "https://data.pyg.org/whl/torch-2.6.0+cu118.html"
format = "flat"
explicit = true

[tool.uv.extra-build-dependencies]
torch-scatter = [{ requirement = "torch", match-runtime = true }]
torch-sparse = [{ requirement = "torch", match-runtime = true }]

[tool.uv]
no-build-isolation-package = ["torch-scatter", "torch-sparse"]

[[tool.uv.dependency-metadata]]
name = "torch-scatter"
version = "2.1.2"
requires-dist = ["torch"]

[[tool.uv.dependency-metadata]]
name = "torch-sparse"
version = "0.6.18"
requires-dist = ["torch"]

